Feature/ct 2
RomanPateichuk/MOVEE pull request #2
Opened 2021-06-04 20:49 UTC by fffbink

2021-06-04 21:29 UTC, DenisKalyanov requested changes

2021-06-04 21:29 UTC, DenisKalyanov commented on index.html
> +            <p id="phone"><a href="">8(029)-999-12-13</a></p>
Лишняя обёртка в виде `р`

2021-06-04 21:29 UTC, DenisKalyanov commented on index.html
> +          <section id="mainTitle">
section Это какой-то смысловой блок. мы не можем в него вставить просто что-то типо заголовка и всё. 
Если хочешь используй div / p

2021-06-04 21:29 UTC, DenisKalyanov commented on index.html
> +    <div id="wrapper">
зачем этот div?
Можно присвоить класс wrapper сразу тегу header. 
Но если ты будешь заливать его жёлтым фоном и расчёт был на это то оставляй.

2021-06-04 21:29 UTC, DenisKalyanov commented on index.html
> +        <div id="callButton">
лишняя обёртка. просто тег img

2021-06-04 21:29 UTC, DenisKalyanov commented on index.html
> +          <div id="mainButton"><a href="">Заказать</a></div>
лишняя обёртка div
Это же больше кнопка чем ссылка. Ты даже в названии использовал Button, а сделал через тег `а`
`<button>`

2021-06-04 21:29 UTC, DenisKalyanov commented on index.html
> +          <div id="divOffset"></div>
для чего этот пустой див?

И имя класса (в твоём случае id - должно нести какой-то смысл, там не должно быть что-то типо div)
Если это будет в качестве тени твоей кнопки, то shadowButton

2021-06-04 21:29 UTC, DenisKalyanov commented on index.html
> +              <img src="img/triggerTwo.png" alt="triggerTwo" />
triggerTwo -  не информативное название

2021-06-04 21:29 UTC, DenisKalyanov commented on index.html
> +        <img id="rectange3" src="img/Rectangle3.png" alt="rectange3" />
rectange3 ?
Это покажется пользователю если картинка не прогрузиться?
И название класса тоже должно отображать сущность, если там мужчина то что-то связанное с man

2021-06-04 21:29 UTC, DenisKalyanov commented on styles/style.css
> +    font-family: "Montserrat-medium", Arial, sans-serif;
так как мы используем этот шрифт везде, то достаточно будет его прописать только в body

2021-06-04 21:29 UTC, DenisKalyanov commented on styles/style.css
> +    width: 304px;
rem

2021-06-04 21:29 UTC, DenisKalyanov commented on styles/style.css
> +    left: 1205px;
Оу, это будет ужасно смотреться на экране шириной 1200px
Вернее его там не будет или появиться полоса прокрутки чтобы посмотреть на мужчину

2021-06-04 21:29 UTC, DenisKalyanov commented on styles/style.css
> +    margin-top: 70px;
на этом месте rem закончились?)

2021-06-04 21:29 UTC, DenisKalyanov commented on styles/style.css
> +  #callButton :hover {
hover с пробелом работает?

2021-06-04 21:29 UTC, DenisKalyanov commented on styles/style.css
> +    opacity: 0.5;
почему у них opacity? там вроде меню не прозрачное, а меняет цвет при наведении

2021-06-04 21:29 UTC, DenisKalyanov commented on styles/style.css
> +@media (min-width: 600px) and (max-width: 800px) {
Сделай обычную вёрстку, потом займись под 320. 
А потом добавишь ещё промежуточные значения, по ходу дела. В те места где вёрстка будет ломаться.

2021-06-04 21:29 UTC, DenisKalyanov commented on styles/style.css
> +@media (min-width: 900px) and (max-width: 1200px) {
удаляй это и делай сразу для десктопа рассчитанного на любое разрешение.

2021-06-05 14:03 UTC, fffbink commented on styles/style.css
> +    left: 1205px;
Двигаться в сторону background-image и позиционировать с помощью background-position?

2021-06-05 20:41 UTC, RomanPateichuk commented on index.html
> +          <div id="divOffset"></div>
Добиться такого эффекта с помощью box-shadow пока не удается.

2021-06-08 07:48 UTC, DenisKalyanov requested changes

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +    margin: 0rem 0rem;
margin: 0;

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +  margin-left: 92.5rem;
margin-left: 92.5rem;
Что будет в том случае если экран будет меньше 1400px,.
Появиться полоса прокрутки, блоки начнут выпадать и т.д.
Делаем в большей степени резиновую вёрстку и адаптируем под другие разрешения

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +  position: absolute;
Ты отталкиваешься от чего? Судя по top left от верхней точки экрана (левой)
Лучше дать кнопке и тени обёртку и дать ей релатив и отталкиваться от неё. Там будет что-то типо top:5px left:5px;

2021-06-08 07:48 UTC, DenisKalyanov commented on fonts/montserrat.css
> +}
Как мы всё это дело сократим:
Пропишем в head
    &lt;link rel="preconnect" href="https://fonts.gstatic.com"&gt;
    &lt;link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&amp;display=swap" rel="stylesheet"&gt;
    
    А сам шрифт пропишем только в body и всё.
    Далее будем изменять только размер/толщину

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +.wrapper {
Ты зря ограничил ширину wrapper.

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +  height: 40.6rem;
Высоту мы не фиксируем. Так как если контента будет больше чем высота он бдует выпадать из блока и всё будет ломаться. Мы можем указать min-height

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +  margin-left: 19.1rem;
Попробуй указывать в %
Это упросит адаптацию под другие разрешения.

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +  font-family: "Montserrat-medium", Arial, sans-serif;
У тебя как бы и так он подключен в body

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +  background-color: red;
Мы не будем так именовать цвета. Используй или rgb()  или #GJ5/...

2021-06-08 07:48 UTC, DenisKalyanov commented on styles/style.css
> +    width: 18.12rem;
Задавай размеры в процентах. Если экран будет меньше чем 18рем. то кнопка всё сломает

2021-06-09 12:46 UTC, merged